config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "foods#index"

  # resources :users do
  #   resources :recipes
  # end

  resources :foods, except: [:update]
  resources :recipes, except: [:update] do
    member do
      put :toggle_public
      delete 'food/:id', to: 'recipes#destroy_food', as: :destroy_food
    end
    resources :recipes_foods, only: %i[new create destroy]
  end
  get '/public_recipes', to: 'recipes#public_recipes'
  get '/shopping_list', to: 'shopping_list#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipes_foods, dependent: :destroy, class_name: 'RecipesFoods'

  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipes_foods, dependent: :destroy, class_name: 'RecipesFoods'

  validates :name, presence: true

  def total_price
    Recipe.find(id)
    total = 0
    recipes_foods.each do |food|
      total = food.food.price
    end
    total
  end
end

app/models/recipes_foods.rb
class RecipesFoods < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def new
    @food = Food.new
  end

  def show
    @food = Food.find_by_id(params[:id])
  end

  def create
    @food = Food.create(foods_params)
    @food.user_id = current_user.id

    if @food.save
      redirect_to foods_path
    else
      render :new, status: 422
    end
  end

  def destroy
    @food = Food.find(params[:id])

    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully deleted.'
    else
      redirect_to foods_path, alert: 'There was an error deleting the Food.'
    end
  end

  private

  def foods_params
    params.require(:food).permit(:id, :name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.includes([:user]).where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = @recipe.user
    @foods = Food.joins(:recipes_foods).where(recipes_foods: { recipe_id: @recipe.id }).includes([:recipes_foods])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    if @recipe.save
      redirect_to recipes_path
    else
      render :new, status: 422
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
    else
      redirect_to recipes_path, alert: 'There was an error deleting the Recipe.'
    end
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user, :recipes_foods).where(public: true).order(created_at: :desc)
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation, :cooking, :desc, :public)
  end
end

app/controllers/recipes_foods_controller.rb
class RecipesFoodsController < ApplicationController
  def new
    @recipe_name = Recipe.find(params[:recipe_id]).name
    @recipes_foods = RecipesFoods.new
  end

  def create
    @recipes_foods = RecipesFoods.new(recipes_foods_params)
    @recipes_foods.recipe_id = params[:recipe_id]

    if @recipes_foods.save
      redirect_to "/recipes/#{params[:recipe_id]}"
    else
      render :new, status: 422
    end
  end

  def destroy
    @recipe = RecipesFoods.find_by(food_id: params[:id], recipe_id: params[:recipe_id])
    if @recipe.destroy
      redirect_to(request.referrer || root_path)
    else
      flash[:error] = 'error'
    end
  end

  private

  def recipes_foods_params
    params.require(:recipes_foods).permit(:food_id, :quantity)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    # @recipes = current_user.recipes.includes(recipes_foods: :food)
    @recipes = current_user.recipes.includes(recipes_foods: :food)
    @all_recipes_foods = @recipes.map(&:recipes_foods).flatten

    @recipes_foods = @all_recipes_foods.select { |recipe| recipe.quantity > recipe.food.quantity }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<div class="foods-wrapper">
  <h1>My Foods</h1>
  <button class="foods__add-food-btn"><%= link_to 'Add Food', '/foods/new' %></button>

  <% if @foods.length.positive?%>
    <table class="foods__table">
      <tr class="foods__table-header-row">
        <th>Food</th>
        <th>Quantity</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
      <tbody>
        <% @foods.each do |food|  %>
          <tr class="foods__table-body-row">
            <td><%= link_to "#{food.name}", food_path(food.id) %></td>
            <td><%= food.quantity%></td>
            <td><%= food.measurement_unit%></td>
            <td><%= food.price%></td>
            <td><%= button_to "delete", food_path(food.id), method: :delete %></td>
          </tr>
        <% end %>
      <tbody>
    </table>

  <% else %>
    <p>No foods to show. Add a food from the button above</p>
  <% end %>
</div>

app/views/foods/new.html.erb
<h1>Add new food</h1>
<% if @food.errors.any? %>
  <div class="post-errors-box">
    <p><%= pluralize(@food.errors.count, "error") %> found:</p>

    <ul class="food-errors-ul">
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<%= form_with path: new_food_path, model: @food, method: :post do |form| %>
  <div class="d-flex flex-column mb-3">
  <div class="col">
  <%= form.label :name%>
  <%= form.text_field :name%>
  </div>
  <div class="col">
  <%= form.label :measurement_unit%>
  <%= form.text_field :measurement_unit%>
  </div>
  <div class="col">
  <%= form.label :price%>
  <%= form.text_field :price%>
  </div>
  <div class="col">
  <%= form.label :quantity%>
  <%= form.number_field :quantity%>
  </div>
  <div class="col">
  <%= form.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/foods/show.html.erb
<h1><%= @food.name%></h1>

<p>Measurement: <%= @food.measurement_unit %></p>
<p>Price: <%= @food.price %></p>
<p> Quantity: <%= @food.quantity %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>My Recipes</h1>
<button type="button" class="btn btn-outline-secondary">
<%= link_to 'Add Recipe', '/recipes/new'%>
</button>

<% if @recipes.length.positive?%>
  <% @recipes.each do |recipe|  %>
    <div class="container cont">
    <div class="row">
      <div class="col">
      <p><%= link_to "#{recipe.name}", recipe_path(recipe.id), class: 'recipe-title' %></p>
      <p><%= button_to "delete", recipe_path(recipe.id), method: :delete, class: "btn btn-danger" %></p>
      </div>
      <div class="col">
      <p><%= recipe.desc%></p>
      </div>
    </div>
  </div>
    <% end %>
  </div>
<% else %>
  <p>No Recipes to show. Add a recipe from the button above</p>
<% end %>

app/views/recipes/new.html.erb
<h1>Add new recipe</h1>
<% if @recipe.errors.any? %>
  <div class="post-errors-box">
    <p><%= pluralize(@recipe.errors.count, "error") %> found:</p>

    <ul class="recipe-errors-ul">
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<%= form_with path: new_recipe_path, model: @recipe, method: :post do |form| %>
<div class="d-flex flex-column mb-3">
  <div class="col">
  <%= form.label :name%>
  <%= form.text_field :name%>
  </div>
  <div class="col">
  <%= form.label :preparation_time%>
  <%= form.text_field :preparation%>
  </div>
  <div class="col">
  <%= form.label :cooking_time%>
  <%= form.text_field :cooking%>
  </div>
  <div class="col">
  <%= form.label :description%>
  <%= form.text_field :desc%>
  </div>
  <div class="col">
  <%= form.label :public%>
<%= form.check_box :public%>
</div>
<div class="col">
<%= form.submit class: "btn btn-primary" %>
</div>
</div>
<% end %>

app/views/recipes/public_recipes.html.erb
<h1 class="text-center">Public Recipies</h1>

<% if @public_recipes.length > 0 %>
<div>
    <% @public_recipes.each do |recipe|%>
        <div class="container cont">
    <div class="row">
      <div class="col">
      <%= link_to "#{recipe.name}", "/recipes/#{recipe.id}", class: 'recipe-title' %>
      <p>by: <%= recipe.user.name%><p>
      </div>
      <div class="col">
      <p>Total food Items: <%= recipe.recipes_foods.length %> </p>
      <p>Total price: $<%= recipe.total_price %></p>
      </div>
    </div>
  </div>
    <% end %>
 </div>
<% else %>
    <h1> No Public Recipies</h1>
<% end %>

app/views/recipes/show.html.erb
<h1 class="text-center"><%= @recipe.name%></h1>

<div class="container">
  <div class="row">
    <div class="row">
    <div class="d-flex justify-content-end">
      <% if @recipe.user_id == current_user.id %>
        <h4 class="m-2">Public</h4>
        <%= button_to toggle_public_recipe_path(@recipe), method: :put do %>
          <% if @recipe.public %>
            <i class="fa fa-toggle-on" style="font-size:40px;color:green"></i>
          <% else %>
            <i class="fa fa-toggle-off" style="font-size:40px;color:green"></i>
          <% end %>
        <% end %>

      <% end %>
    </div>
    <p>Preparation time: <%= @recipe.preparation%></p>
    <p>Cooking time: <%= @recipe.cooking%></p>
    <p>Description: <%= @recipe.desc%></p>
    
    <% if @recipe.user_id == current_user.id %>
    <div class="d-flex justify-content-between">
    <button class="generate-shopping-list"><%= link_to "Generate Shopping List", shopping_list_path %></button>
      <button class="add-ingredient"><%= link_to 'Add Ingredient', "/recipes/#{@recipe.id}/recipes_foods/new" %></button>
    </div>
    <% end %>

    </div>
    <div class="row">
    <% if @foods.length.positive?%>
    <table class="foods__table">
      <tr class="foods__table-header-row">
        <th>Food</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
      <tbody>
        <% @foods.each do |food|  %>
          <tr id="<%= dom_id food %>", class="foods__table-body-row">
             <td><%= food.name %></td>
            <td><%= food.recipes_foods.select {|recipe| recipe.food_id == food.id}[0].quantity%> <%= food.measurement_unit%></td>
            <td>$<%= food.price%></td>
            <% if current_user.id == @recipe.user.id%>
            <td>
                <%= button_to "Remove", recipe_recipes_food_path(@recipe.id, food.id), method: :delete %>
            </td> 
            <% end %>
          </tr>
        <% end %>
      <tbody>
    </table>

  <% else %>
    <p>No Ingredients to show. Add an ingredient from the button above</p>
  <% end %>
    </div>
  </div>
</div>

app/views/recipes_foods/new.html.erb
<% if @recipes_foods.errors.any? %>
  <div>
    <p><%= pluralize(@recipes_foods.errors.count, "error") %> found:</p>

    <ul>
      <% @recipes_foods.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<%= form_with model: @recipes_foods, url: "/recipes/#{params[:recipe_id]}/recipes_foods", method: :post do |form| %>
<h1>Add Ingredient for <%= @recipe_name %></h1>
<div class="d-flex flex-column mb-3">
<div class="col">
<%= form.label :quantity %>
<%= form.number_field :quantity %>
</div>
<div class="col">
<%= form.label :food_id%>
<%= form.select :food_id, Food.all.map {|f| [f.name, f.id]} %>
</div>
<div class="col">
<%= form.submit 'Add Ingredient', class: "btn btn-primary" %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/foods">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/foods">Foods</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/shopping_list">Shopping List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/recipes">Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/public_recipes">Public Recipes</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shopping_list/index.html.erb
<h1 class="text-center">Shopping List</h1>
<div class="container">
<div class="row">
<div class="d-flex justify-content-center shop-title">
  <span>
    Amount of food items to buy: <span><%= @recipes_foods.length %></span>
  </span>
  <span>
    Total value of food needed: <span>$<%= @recipes_foods.map {|r| r.food.price * (r.quantity - r.food.quantity) }.sum %></span>
  </span>
  </div>
</div>
<div class="row">
<table class="food__tabel">
  <thead>
    <tr class="foods__table-header-row">
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes_foods.each_with_index do | recipe,index|%>
      <tr class="foods__table-body-row">
        <td><%= recipe.food.name %></td>

        <% if recipe.food.user_id == current_user.id %>
          <td><%= recipe.quantity - recipe.food.quantity %> <%= recipe.food.measurement_unit %></td>
        <% else %>
          <td><%= recipe.quantity %> <%= recipe.food.measurement_unit %></td>
        <% end %>
        
        
        
        <td>$<%= recipe.food.price %></td>
        <td>$<%= recipe.food.price.to_i * (recipe.quantity - recipe.food.quantity) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/users/index.html.erb
<div class='main-container'>
<ul>
<% @users.each do |user| %>
    <li class='user-list'>
    <div class='user-box'>
    <div class='name'><%= user.name %></div>
    </div>
    </li>
    <% end %>
</ul>
</div>